export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_PRODUCTS_BY_SLUG = 'GET_PRODUCTS_BY_SLUG';
export const GET_PRODUCT_PAGE_REQUEST='GET_PRODUCT_PAGE_REQUEST';
export const GET_PRODUCT_PAGE_SUCCESS='GET_PRODUCT_PAGE_SUCCESS';
export const GET_PRODUCT_PAGE_FAILURE='GET_PRODUCT_PAGE_FAILURE';
export const GET_PRODUCT_DETAILS_BY_ID_REQUEST = 'GET_PRODUCT_DETAILS_BY_ID_REQUEST';
export const GET_PRODUCT_DETAILS_BY_ID_SUCCESS='GET_PRODUCT_DETAILS_BY_ID_SUCCESS';
export const GET_PRODUCT_DETAILS_BY_ID_FAILURE='GET_PRODUCT_DETAILS_BY_ID_FAILURE';

export const NEW_ADDRESS_REQUEST = "NEW_ADDRESS_REQUEST";
export const NEW_ADDRESS_SUCCESS = "NEW_ADDRESS_SUCCESS";
export const NEW_ADDRESS_FAIL = "NEW_ADDRESS_FAIL";

export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
export const  SEARCH_FAIL = 'SEARCH_FAIL';
export const SEARCH_REQUEST= 'SEARCH_REQUEST';
