export const ALL_PRODUCT_SLIDER_REQUEST = 'ALL_PRODUCT_SLIDER_REQUEST';
export const ALL_PRODUCT_SLIDER_SUCCESS = 'ALL_PRODUCT_SLIDER_SUCCESS';
export const ALL_PRODUCT_SLIDER_FAIL = 'ALL_PRODUCT_SLIDER_FAIL';

